<?php

// CHECK TO SEE IF USER EXISTS	
// CHECK TO SEE IF PLOT IS EXISTS
// CHECK TO SEE IF PLOT IS ALREADY OWNED
// UPDATE "user_id" TO "owner_id" FIELD OF PLOT ... THIS WILL LOCK THE TRANSACTION

// GET TOTAL QUBITS in PLOT
// GET TOTAL QUBITS "qubits_held" by USER
// ADD TOTAL QUBITS in PLOT to QUBITS HELD by USER

// UPDATE USER "qubits_held" by USER with NEW TOTAL
// ADD PLOT ID TO USER PLOTS along with Date added etc
	
	
?>